import React, { useMemo, useRef } from "react";

function computeDiff(prev: string, next: string): { start: number; delCount: number; insText: string } {
  if (prev === next) return { start: 0, delCount: 0, insText: "" };

  let i = 0;
  while (i < prev.length && i < next.length && prev[i] === next[i]) i++;

  let jPrev = prev.length - 1;
  let jNext = next.length - 1;
  while (jPrev >= i && jNext >= i && prev[jPrev] === next[jNext]) { jPrev--; jNext--; }

  const delCount = (jPrev - i + 1) < 0 ? 0 : (jPrev - i + 1);
  const insText = next.slice(i, jNext + 1);
  return { start: i, delCount, insText };
}

export default function Editor(props: {
  value: string;
  live: boolean;
  onEdit: (next: string, meta: { diff: typeof computeDiff }) => void;
}) {
  const last = useRef(props.value);

  // keep last updated when external replay changes happen
  useMemo(() => { last.current = props.value; }, [props.value]);

  return (
    <div>
      {!props.live && <div className="badge" style={{ marginBottom: 10 }}>Replay mode (read-only)</div>}
      <textarea
        rows={10}
        value={props.value}
        readOnly={!props.live}
        onChange={(e) => {
          const next = e.target.value;
          last.current = next;
          props.onEdit(next, { diff: computeDiff });
        }}
        placeholder="Type here…"
      />
      <small>CRDT ops are generated by diffing edits into insert/delete batches.</small>
    </div>
  );
}